---
swagger: "2.0"
info:
  description: "This is an API for chess games, openings, and moves"
  version: "1.0.0"
  title: "chess-flashcards"
host: "localhost:5000"
basePath: "/api/v1"
schemes:
- "https"
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /moves:
    get:
      summary: "Get moves for the given position"
      operationId: "moves_get"
      parameters:
      - name: "fen"
        in: "query"
        description: "FEN of the position to find moves for"
        required: true
        type: "string"
      - name: "flags"
        in: "query"
        description: "Restrict the moves to certain types"
        required: false
        type: "array"
        items:
          type: "string"
          enum:
          - "check"
          - "checkmate"
          - "stalemate"
          - "capture"
          - "enpessant"
          - "castle"
      responses:
        200:
          description: "Successfully found moves"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Move"
        400:
          description: "Position is not valid"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /openings:
    get:
      summary: "Get all ECO openings"
      operationId: "openings_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successfully got all ECO openings"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Opening"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /openings/{id}:
    get:
      summary: "Get an opening and its variants by id"
      operationId: "openings_id_get"
      parameters:
      - name: "id"
        in: "path"
        description: "ECO id e.g. C42"
        required: true
        type: "string"
        pattern: "[A-E][0-9]{2}"
        x-regex: "[A-E][0-9]{2}"
        x-modifiers: []
      responses:
        200:
          description: "Successfully found requested opening"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Opening"
        400:
          description: "Invalid ECO id supplied"
        404:
          description: "Opening not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /openings/search:
    get:
      summary: "Fuzzy search for openings"
      operationId: "openings_search_get"
      parameters:
      - name: "term"
        in: "query"
        description: "Search term to use in search"
        required: true
        type: "string"
      responses:
        200:
          description: "Search completed successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Opening"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Move:
    type: "object"
    required:
    - "dst"
    - "piece"
    - "src"
    properties:
      piece:
        type: "string"
        format: "[PNBRQKpnbrqk]"
        description: "The piece being moved, white pieces are indicated by uppercase"
      src:
        type: "string"
        format: "[a-g][1-8]"
        description: "The square that the piece was on at the start of the move"
      dst:
        type: "string"
        format: "[a-g][1-8]"
        description: "The square that the piece is on at the end of the move"
      is_check:
        type: "boolean"
        description: "True if the move results in check, false otherwise"
      is_mate:
        type: "boolean"
        description: "True if the move results in checkmate, false otherwise"
      is_stalemate:
        type: "boolean"
        description: "True if the move results in stalemate, false otherwise"
      is_enpessant:
        type: "boolean"
        description: "True if the move was an en pessant capture"
      is_castle:
        type: "boolean"
        description: "True if the move is a castle"
      captured_piece:
        type: "string"
        format: "[PNBRQKpnbrqk]"
        description: "The piece that was captured if one was captured"
      fen_after:
        type: "string"
        description: "The fen of the board before the move"
      fen_before:
        type: "string"
        description: "The fen of the board at the end of the move"
    description: "Represents a single move that a player can make during a turn"
    example:
      fen_before: "fen_before"
      is_mate: true
      is_stalemate: true
      dst: "dst"
      piece: "piece"
      src: "src"
      captured_piece: "captured_piece"
      fen_after: "fen_after"
      is_castle: true
      is_check: true
      is_enpessant: true
  Opening:
    type: "object"
    required:
    - "id"
    - "moves"
    - "name"
    properties:
      name:
        type: "string"
        description: "The human friendly name for the opening"
      id:
        type: "string"
        description: "The ECO id for the opening, e.g. E04"
        pattern: "[A-E][0-9]{2}"
        x-regex: "[A-E][0-9]{2}"
        x-modifiers: []
      moves:
        type: "array"
        description: "The mainline moves that identify this opening"
        items:
          $ref: "#/definitions/Move"
      variants:
        type: "array"
        description: "Variants of the opening if any exist"
        items:
          $ref: "#/definitions/OpeningVariant"
    description: "An ECO chess opening"
    example:
      moves:
      - fen_before: "fen_before"
        is_mate: true
        is_stalemate: true
        dst: "dst"
        piece: "piece"
        src: "src"
        captured_piece: "captured_piece"
        fen_after: "fen_after"
        is_castle: true
        is_check: true
        is_enpessant: true
      - fen_before: "fen_before"
        is_mate: true
        is_stalemate: true
        dst: "dst"
        piece: "piece"
        src: "src"
        captured_piece: "captured_piece"
        fen_after: "fen_after"
        is_castle: true
        is_check: true
        is_enpessant: true
      name: "name"
      id: "id"
      variants:
      - moves:
        - fen_before: "fen_before"
          is_mate: true
          is_stalemate: true
          dst: "dst"
          piece: "piece"
          src: "src"
          captured_piece: "captured_piece"
          fen_after: "fen_after"
          is_castle: true
          is_check: true
          is_enpessant: true
        - fen_before: "fen_before"
          is_mate: true
          is_stalemate: true
          dst: "dst"
          piece: "piece"
          src: "src"
          captured_piece: "captured_piece"
          fen_after: "fen_after"
          is_castle: true
          is_check: true
          is_enpessant: true
        name: "name"
      - moves:
        - fen_before: "fen_before"
          is_mate: true
          is_stalemate: true
          dst: "dst"
          piece: "piece"
          src: "src"
          captured_piece: "captured_piece"
          fen_after: "fen_after"
          is_castle: true
          is_check: true
          is_enpessant: true
        - fen_before: "fen_before"
          is_mate: true
          is_stalemate: true
          dst: "dst"
          piece: "piece"
          src: "src"
          captured_piece: "captured_piece"
          fen_after: "fen_after"
          is_castle: true
          is_check: true
          is_enpessant: true
        name: "name"
  OpeningVariant:
    type: "object"
    properties:
      name:
        type: "string"
        description: "The human friendly name for the variant"
      moves:
        type: "array"
        description: "The moves that identify this variant"
        items:
          $ref: "#/definitions/Move"
    description: "A named variation of an ECO opening"
    example:
      moves:
      - fen_before: "fen_before"
        is_mate: true
        is_stalemate: true
        dst: "dst"
        piece: "piece"
        src: "src"
        captured_piece: "captured_piece"
        fen_after: "fen_after"
        is_castle: true
        is_check: true
        is_enpessant: true
      - fen_before: "fen_before"
        is_mate: true
        is_stalemate: true
        dst: "dst"
        piece: "piece"
        src: "src"
        captured_piece: "captured_piece"
        fen_after: "fen_after"
        is_castle: true
        is_check: true
        is_enpessant: true
      name: "name"
